# Generated by Django 3.1.3 on 2021-10-05 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211004_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_price',
            new_name='bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
