# Generated by Django 3.1.3 on 2021-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211005_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
