# Generated by Django 3.1.3 on 2021-10-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211005_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='auction',
            new_name='auctions',
        ),
    ]
