# Generated by Django 3.1.3 on 2021-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211007_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
