# Generated by Django 3.1.3 on 2021-10-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='lister',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
