# Generated by Django 3.1.3 on 2021-10-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
    ]
